# Generated by Django 6.1.1 on 2026-09-13 17:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ingrediente')),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('l', 'L'), ('un', 'un')], max_length=2, verbose_name='unidade')),
                ('target_stock', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='A quantidade não pode ser negativa.'), django.core.validators.MaxValueValidator(Decimal('999999999.999'), message='A quantidade não pode ser maior que 999999999.999.')], verbose_name='meta de estoque')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='A quantidade não pode ser negativa.'), django.core.validators.MaxValueValidator(Decimal('999999999.999'), message='A quantidade não pode ser maior que 999999999.999.')], verbose_name='quantidade inicial')),
                ('period_consumption', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='A quantidade não pode ser negativa.'), django.core.validators.MaxValueValidator(Decimal('999999999.999'), message='A quantidade não pode ser maior que 999999999.999.')], verbose_name='consumo do período')),
                ('expiration_date', models.DateField(verbose_name='data de validade')),
                ('ran_out_before_month_end', models.BooleanField(default=False, verbose_name='acabou antes do fim do mês')),
            ],
            options={
                'verbose_name': 'fotografia de ingrediente',
                'verbose_name_plural': 'fotografias de ingredientes',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('target_stock__gte', Decimal('0'))), name='inventory_target_nonnegative'), models.CheckConstraint(condition=models.Q(('initial_quantity__gte', Decimal('0'))), name='inventory_initial_nonnegative'), models.CheckConstraint(condition=models.Q(('period_consumption__gte', Decimal('0'))), name='inventory_consumption_nonnegative'), models.CheckConstraint(condition=models.Q(('period_consumption__lte', models.F('initial_quantity'))), name='inventory_consumption_lte_initial')],
            },
        ),
    ]
